seed: 42
work_dir: runs/resnet18_cifar10
mixed_precision: true
epochs: 2
log_interval: 50
ckpt_interval: 1

model:
  name: classification_model
  backbone:
    name: resnet18
    pretrained: false
  head:
    name: linear_classifier
    in_features: 512
    num_classes: 10

loss:
  name: cross_entropy

optimizer:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  name: StepLR
  step_size: 1
  gamma: 0.7

data:
  train:
    name: CIFAR10
    root: data
    train: true
    download: true
    transforms:
      - name: RandomCrop
        size: 32
        padding: 4
      - name: RandomHorizontalFlip
        p: 0.5
      - name: ToTensor
      - name: Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2470, 0.2435, 0.2616]
  val:
    name: CIFAR10
    root: data
    train: false
    download: true
    transforms:
      - name: ToTensor
      - name: Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2470, 0.2435, 0.2616]
  train_loader:
    batch_size: 128
    shuffle: true
    num_workers: 4
    pin_memory: true
  val_loader:
    batch_size: 256
    shuffle: false
    num_workers: 4
    pin_memory: true
